### PR TITLE
attempt of getting a website description 

### PR DESCRIPTION
**Pull request by veroandreo**
I changed `config.toml` as an attempt to get a description and solve #205

### CODE REVIEW

**Comment by neteler** [comment]
According to https://gohugo.io/variables/site/#example-siteparams
the description line must go below
[params]

(I'm just guessing)

**Comment by veroandreo** [comment]
I moved the description under `[params]` in b1853fbf1828491fbc5a91472ae958558d7d0e87 but no success either.

**Comment by mlennert** [comment]
On 29/07/20 01:16, Veronica Andreo wrote:
> I moved the description under |[params]| in b1853fb 
> <https://github.com/OSGeo/grass-website/commit/b1853fbf1828491fbc5a91472ae958558d7d0e87> 
> but no success either.
> 

How do you actually test whether it works ?

**Comment by veroandreo** [comment]
> On 29/07/20 01:16, Veronica Andreo wrote: I moved the description under |[params]| in [b1853fb](https://github.com/OSGeo/grass-website/commit/b1853fbf1828491fbc5a91472ae958558d7d0e87) <[b1853fb](https://github.com/OSGeo/grass-website/commit/b1853fbf1828491fbc5a91472ae958558d7d0e87)> but no success either.
> How do you actually test whether it works ?

In firefox, I check the source code of the local build of the home page and the description does not appear there in the meta tag... see https://github.com/OSGeo/grass-website/issues/205#issuecomment-665345550

**Pull request merged**
