### PR TITLE
releases: add missing release entries

### PR DESCRIPTION
**Pull request by neteler**
- 7.8.6, 7.8.7
- 8.0.0
- Creation of the GRASS GIS 8.2 release branch

image

### CODE REVIEW

**Comment by veroandreo** [comment]
Thanks! We should include 8.0.1 too, no?

**Comment by neteler** [comment]
> Thanks! We should include 8.0.1 too, no?

Oh sure, done.

**Review by veroandreo — APPROVED** [review]
Thanks again! I see u added creation of 8.2 branch. Perhaps you can also add creation of 8.0 branch before merging? I realize only now

**Comment by neteler** [comment]
> Perhaps you can also add creation of 8.0 branch before merging?

Yes, done. The precise hash I don't know, though.

**Pull request merged**
