### PR TITLE
Modify colors of learn page

### PR DESCRIPTION
**Pull request by withgaurav**
In the learn page as we have discussed I have changed the colors @veroandreo

### CODE REVIEW

**Comment by withgaurav** [comment]
This learn page looks like this

image







After hover this page looks like

image

Please give me a review about this. @veroandreo

**Comment by veroandreo** [comment]
This is what I see after compiling your branch

image


Are you sure you are making the changes from the latest master branch and not over your previous changes?? Some other things remain undesirably affected as in the former PR...

1. the titles' color
image
2. default and hover color of buttons
image
3. well, this is odd
image
4. background
image

**Comment by neteler** [comment]
> I will make a new pull request and do the changes

You may just modify this pull request, no need for a new one...

**Comment by petrasovaa** [comment]
Let's close this PR for now, @withgaurav you can always open a new one.

**Pull request closed without merging**
