### PR TITLE
Add Archlinux based distribution link in Readme 8.4.0

### PR DESCRIPTION
**Pull request by kikislater**
Add Archlinux based distribution link.

Also available as an autobuild for arch4edu repository : https://github.com/arch4edu/arch4edu/

### CODE REVIEW

**Review by neteler — APPROVED** [review]
Thanks!

**Comment by neteler** [comment]
> Also available as an autobuild for arch4edu repository : https://github.com/arch4edu/arch4edu/

Would you mind to add this to
https://grasswiki.osgeo.org/wiki/Compile_and_Install#Arch_Linux
so that it doesn't get lost?

**Comment by kikislater** [comment]
> > Also available as an autobuild for arch4edu repository : https://github.com/arch4edu/arch4edu/
> 
> Would you mind to add this to https://grasswiki.osgeo.org/wiki/Compile_and_Install#Arch_Linux so that it doesn't get lost?

Done!

**Comment by neteler** [comment]
> > > Also available as an autobuild for arch4edu repository : https://github.com/arch4edu/arch4edu/
> > 
> > 
> > Would you mind to add this to https://grasswiki.osgeo.org/wiki/Compile_and_Install#Arch_Linux so that it doesn't get lost?
> 
> Done!

Did you actually save your changes? There is no editing trace in
https://grasswiki.osgeo.org/w/index.php?title=Compile_and_Install&action=history

**Comment by neteler** [comment]
> Yes you're right, there is a verification box at the top of the page I didn't filled !

Perfect, now I can see the Wiki changes (the box is our own captcha to keep spammers out).

**Pull request merged**
