### PR TITLE
added events to news page

### PR DESCRIPTION
**Pull request by lucadelu**
new pull request for #64

### CODE REVIEW

**Comment by veroandreo** [comment]
@lucadelu would you attach a screenshot, please? It's then much easier to visualize changes and give feedback

**Comment by lucadelu** [comment]
next_events

**Comment by veroandreo** [comment]
Thanks for this @lucadelu :)

Is it possible to add a lil padding on the left of "Next events" title? It appears to me as too close to the border of the box... maybe it's just my perception dunno

And, it occurs to me now, that since "Next events" will at most contain 2 items, we could put it above the twitter feed so we make sure that visitors will see it... and the twitter feed will still be visible too... what do you say @neteler  @mlennert ?

**Comment by lucadelu** [comment]
> Thanks for this @lucadelu :)
> 
> Is it possible to add a lil padding on the left of "Next events" title? It appears to me as too close to the border of the box... maybe it's just my perception dunno
> 

ok, so I suggest to move also @grassgis twitter title

> And, it occurs to me now, that since "Next events" will at most contain 2 items, we could put it above the twitter feed so we make sure that visitors will see it... and the twitter feed will still be visible too... what do you say @neteler @mlennert ?

I will display 3 items, now there are two only because I added only two events after today

**Comment by mlennert** [comment]
> Thanks for this @lucadelu :)
> 
> Is it possible to add a lil padding on the left of "Next events" title? It appears to me as too close to the border of the box... maybe it's just my perception dunno
> 
> And, it occurs to me now, that since "Next events" will at most contain 2 items, we could put it above the twitter feed so we make sure that visitors will see it... and the twitter feed will still be visible too... what do you say @neteler  @mlennert ?
>  
> 

I think it really depends on where we think we will be more active: Twitter or next events. I do have the feeling that in average we have more on Twitter, and more directly linked to GRASS itself, while events are mostly broader, so with that in mind I think the order is good as is.

BTW, we should take out the foss4g event announcements before taking the website public as they are cancelled.

**Comment by lucadelu** [comment]
Going to merge, in case continue to discuss about position in #54

**Pull request merged**
