### PR TITLE
added events, #TODO fix allnews.html filter

### PR DESCRIPTION
**Pull request by lucadelu**

### CODE REVIEW

**Comment by neteler** [comment]
Any plans to merge this? (in conflict at time, needs a rebase)

**Comment by lucadelu** [comment]
Not yet since there is still a problem, needed a check from @nbozon

**Comment by neteler** [comment]
> Not yet since there is still a problem, needed a check from @nbozon

There is a conflict in the PR. Please also described (or point to) what @nbozon should check

**Comment by lucadelu** [comment]
> > Not yet since there is still a problem, needed a check from @nbozon
> 
> There is a conflict in the PR. Please also described (or point to) what @nbozon should check

I hope that I rebase correctly, I also fixed the problem with events, for my side the pull request is able to merge

**Comment by neteler** [comment]
> I hope that I rebase correctly,

I am afraid no.

> I also fixed the problem with events, for my side the pull request is able to merge

Do you mind to redo this PR?
It changes 438 files which is rather unlikely... a lot of things already done are again in this PR. It may case a major mess in the repo (history).

**Comment by lucadelu** [comment]
> > I hope that I rebase correctly,
> 
> I am afraid no.
> 

Eh I suspect this

> > I also fixed the problem with events, for my side the pull request is able to merge
> 
> Do you mind to redo this PR?

Yes, I will close this one and do a new one

> It changes 438 files which is rather unlikely... a lot of things already done are again in this PR. It may cause a major mess in the repo (history).

Yes sure, but what is the right way to do update a branch? 

I did this:
- git pull into branch
- git rebase upstream/master
- git push (but git told me to pull again and in this moment it create all the mess)

**Pull request closed without merging**
