### PR TITLE
created donation page

### PR DESCRIPTION
**Pull request by lucadelu**

### CODE REVIEW

**Comment by landam** [comment]
> > I would put the 'why donate' section at the top, with the 'GRASS GIS is an affiliated project...' at the end of that section.
> 
> Is it fine for me, for the others?

+1

**Comment by veroandreo** [comment]
> > > I would put the 'why donate' section at the top, with the 'GRASS GIS is an affiliated project...' at the end of that section.
> > 
> > 
> > Is it fine for me, for the others?
> 
> +1

I agree and probably we could merge the content of the first paragraph with the text under "why donate" section

**Comment by lucadelu** [comment]
page updated, ready to merge?

**Comment by mlennert** [comment]
> page updated, ready to merge?

Please go ahead and merge. Any edits can then be done directly in the merged page.

**Pull request merged**
