### PR TITLE
WIP: Move "get involved" section from development to contribute landing page

### PR DESCRIPTION
**Pull request by veroandreo**
This PR also replaces the images removed in #72 with fa icons as suggested in #114. I've noticed by trial and error that the maximum size for fa icons is 5x, would it be possible to increase the size a lil bit further??

### CODE REVIEW

**Comment by veroandreo** [comment]
ok, I used this PR to solve #116 as well... I just removed the empty md file

**Comment by lucadelu** [comment]
> This PR also replaces the images removed in #72 with fa icons as suggested in #114. I've noticed by trial and error that the maximum size for fa icons is 5x, would it be possible to increase the size a lil bit further??

Instead I put back images in #119, sorry I didn't see this pull request before

**Comment by neteler** [comment]
Just don't merge #119

**Comment by veroandreo** [comment]
Since there are already 2 approvals, I am merging this one. We can undo or create a different PR if the majority disagrees.

**Comment by veroandreo** [comment]
> great ! +1 to merge. We can also add some of the theme classes to add green or any other color to the icons if you would like -

I'd rather like to make them a little larger, but 6x, 7x and so on, produce tiny icons instead. Any suggestions?

**Pull request merged**
