### PR TITLE
Fred Limp's retirement homage note

### PR DESCRIPTION
**Pull request by veroandreo**
This PR is intended as a news post to honor Fred Limp on his retirement. Thanks @cmbarton and @hmitaso for the text and pics. This is how the news look like:

image

I did not find a nice way to also include the "Growing GRASS with Fred Limp" pic.

His retirement gathering is on June 4th, according to [this](https://news.uark.edu/articles/56948/fred-limp-founding-director-of-center-for-advanced-spatial-technologies-to-retire), so we might then decide when to publish our note.

### CODE REVIEW

**Comment by neteler** [comment]
(for reference, the "Growing GRASS with Fred Limp" column is found here:

https://grass.osgeo.org/files/grassclip6_2_92.pdf, pp.15-16)

**Comment by hellik** [comment]
>I did not find a nice way to also include the "Growing GRASS with Fred Limp" pic.

what about instead of the training pic?

**Comment by neteler** [comment]
Attached a slightly color polished version of p.15:

fred_limp_grassclip6_2_1992

**Comment by cmbarton** [comment]
Looks very good. Thanks for putting this together.

**Review by cmbarton — APPROVED** [review]
Looks good. I couldn't tell if you added the link that Marco found yet.

**Comment by veroandreo** [comment]
> Looks good. I couldn't tell if you added the link that Marco found yet.

It's here: https://github.com/OSGeo/grass-website/pull/258/commits/63d8ceff5cc234f96a21e9d6a933eda439ee66ce

**Comment by veroandreo** [comment]
> Attached a slightly color polished version of p.15:
> 
> fred_limp_grassclip6_2_1992

Thanks Markus! Do you suggest to include it in the news post? 

I find it a bit too large. And in general, in terms of pics/text ratio, we have too many pics for the amount of text. It's my esthetic feeling only. Others might think different.

> > I did not find a nice way to also include the "Growing GRASS with Fred Limp" pic.
> 
> what about instead of the training pic?

too many pics; i tried... it does not look good

**Comment by veroandreo** [comment]
> > I did not find a nice way to also include the "Growing GRASS with Fred Limp" pic.
> 
> what about instead of the training pic?

I tried, it doesn't look good... sometimes, less is more ;)

**Comment by neteler** [comment]
> > what about instead of the training pic?
> I tried, it doesn't look good... sometimes, less is more ;)

It could also just be the upper half of the p15 scan... since the link to the PDF is there it'd be just a teaser ...

**Comment by cmbarton** [comment]
Could just put in a hot link to the page.

**Comment by veroandreo** [comment]
> Could just put in a hot link to the page.

what do you mean by hot link?

**Comment by veroandreo** [comment]
> > > what about instead of the training pic?
> > > I tried, it doesn't look good... sometimes, less is more ;)
> 
> It could also just be the upper half of the p15 scan... since the link to the PDF is there it'd be just a teaser ...

Wherever I add it, the news will look too full of images IMHO. I really struggled to get the current layout.

Where would you like to add it? Or maybe you prefer to remove other pics to add this one instead?

**Comment by cmbarton** [comment]
I meant just a link to the Growing Grass documents when they are mentioned, but without any image.

**Comment by veroandreo** [comment]
> I meant just a link to the Growing Grass documents when they are mentioned, but without any image.

Ah! Yes, that's already there as pointed in a previous response (see this coomit https://github.com/OSGeo/grass-website/commit/63d8ceff5cc234f96a21e9d6a933eda439ee66ce)

**Comment by cmbarton** [comment]
> > I meant just a link to the Growing Grass documents when they are mentioned, but without any image.
> 
> Ah! Yes, that's already there as pointed in a previous response (see this coomit [63d8cef](https://github.com/OSGeo/grass-website/commit/63d8ceff5cc234f96a21e9d6a933eda439ee66ce))

OK. Didn't see that

**Comment by neteler** [comment]
Looks fine without the scan and the linked PDF should do it!

**Review by neteler — APPROVED** [review]

**Comment by hmitaso** [comment]
Michael, please let Fred know about the post, I doubt he remebers me, thank you, Helena

> On Jun 3, 2021, at 11:23 AM, Michael Barton ***@***.***> wrote:
> 
> 
> Looks great @veroandreo. Thanks. @hmitaso do want to send Fred a note letting him know about this? Or should I?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Helena Mitasova
Professor at the Department of Marine, 
Earth, and Atmospheric Sciences
Associate director and faculty fellow at the Center for Geospatial Analytics
North Carolina State University
Raleigh, NC 27695-8208
***@***.***

"All electronic mail messages in connection with State business which are sent to or received by this account are subject to the NC Public Records Law and may be disclosed to third parties.”

**Pull request merged**
