### PR TITLE
GRASS 8.4.0 news: update Ubuntu link + add Nix

### PR DESCRIPTION
**Pull request by landam**
This PR:

- modify UbuntuGIS link to show grass packages only
- add Nix link

### CODE REVIEW

**Review by echoix — APPROVED** [review]

**Comment by echoix** [comment]
Checked the links, points correctly

**Review by veroandreo — APPROVED** [review]

**Comment by landam** [comment]
The recent changes seems to be not propagated, see https://grass.osgeo.org/news/2024_07_27_grass_gis_8_4_0_released/.

**Comment by neteler** [comment]
I have checked, the cronjob logs are in mail local mailbox on the website.
Error message:

```
Date: Sun, 04 Aug 2024 00:30:02 +0000
From: Cron Daemon <root@grass>
To: neteler@grass
Subject: Cron <neteler@grass> nice sh /home/neteler/cronjobs/hugo_clean_and_update_job.sh

>From https://github.com/OSGeo/grass-website
 * branch            master     -> FETCH_HEAD
Already up to date.
nice: ‘hugo’: No such file or directory
```

I have now added a softlink to `/usr/local/bin/` and will check at the next crontab run if this solved the problem.

Meanwhile I have manually triggered the hugo script.

**Comment by neteler** [comment]
> I have now added a softlink to `/usr/local/bin/` and will check at the next crontab run if this solved the problem.

I missed that path issue here:
https://github.com/OSGeo/grass-website/issues/394#issuecomment-2176725047

**Pull request merged**
