### PR TITLE
WIP: Learn landing page and subsections

### PR DESCRIPTION
**Pull request by veroandreo**
This is WIP. The PR contains a first draft for the `Learn` landing page and some minor fixes and typos corrected in Learn subsections. 

Among things to come/ideas:
- ~Add one more row to Learn landing page with a couple more things. Maybe Martin's course and something about OBIA or CNN in GRASS (other ideas are welcome) ->> my plan is to put cool GRASS stuff there~
- Split list of tutorials in English according to topics? (with some nicer styling maybe, @nbozon suggestions?)
- ~Add some screenshots to `First time users` and `Tutorials`~
- ~Add some missing tutorials in learn/tutorial and change some of the featured videos to avoid repetitions~
- ~Add other books with their covers as in https://grass.osgeo.org/documentation/books/~

### CODE REVIEW

**Comment by neteler** [comment]
I tried to apply this PR locally but it fails. Do I have to apply another PR beforehand?
Or, would you mind to add a screenshot here? Thx

**Comment by veroandreo** [comment]
> I tried to apply this PR locally but it fails. Do I have to apply another PR beforehand?
> Or, would you mind to add a screenshot here? Thx

Here some screenshots:

Learn landing page
image

Tutorials
image

Books
image

**Comment by ninsbl** [comment]
> Here some screenshots:


Looks pretty good to me!
Maybe just the colors of the icons in the row: Write your addon, GRASS in the cloud, Try GRASS online should be adjusted to each other?

**Comment by veroandreo** [comment]
> > Here some screenshots:
> 
> Looks pretty good to me!
> Maybe just the colors of the icons in the row: Write your addon, GRASS in the cloud, Try GRASS online should be adjusted to each other?

Right, I'll remove background from actinia logo (you mean to change color too?) and try setting all to light green since once you click on them they change to grass green. What do you think?

**Comment by ninsbl** [comment]
> Right, I'll remove background from actinia logo (you mean to change color too?) and try setting all to light green since once you click on them they change to grass green. What do you think?

Yes, I would remove the grey background. However, the three icons / logos in that row each has another green. That just looks a bit strange...

**Comment by lucadelu** [comment]
> I tried to apply this PR locally but it fails. Do I have to apply another PR beforehand?

I can apply it

**Comment by lucadelu** [comment]
> 
> Right, I'll remove background from actinia logo (you mean to change color too?) and try setting all to light green since once you click on them they change to grass green. What do you think?

Yes please, If you have css or html problem chat me or submit the changes and later we will fix them

**Comment by veroandreo** [comment]
the last row in `Learn` landing page now looks like this:

image

but the problem is that logos because they are images (and not fa) do not change color when you go over them with the mouse or after clicking on them as the "plug" fa does (see images below). So, we could an image to replace the "plug" or find the way to put it outside the link (I tried, but didn't get the expected results)

image

image

**Comment by veroandreo** [comment]
I added one more row to `Learn` landing page with a link to Tangible Landscape and the CNN presentation by Ondrej. It now looks like this:

image

I also uploaded grey and grass green versions of actinia and www images, so we can homogenize the behavior with CSS (@lucadelu)

**Comment by veroandreo** [comment]
I did a couple more changes, mostly adding screenshots to newcomers and tutorial pages. I merge so it becomes visible and then we can further enhance or change.

**Pull request merged**
