### PR TITLE
Add ZMI Stone Town v.surf.icw example

### PR DESCRIPTION
**Pull request by smathermather**
Zanzibar Mapping Initiative data processed in OpenDroneMap and interpolated respecting building footprints using v.surf.icw.
image

### CODE REVIEW

**Comment by smathermather** [comment]
I don't know if it's desirable to change the wording for the lidar section, but this pull request includes a commit that does so.

**Comment by lucadelu** [comment]
Make sense to me

**Review by veroandreo — APPROVED** [review]
Great screenshot and cool stuff!!

**Review by neteler — APPROVED** [review]
Great work!

**Comment by neteler** [comment]
Beautiful! https://grass.osgeo.org/learn/gallery/#lidar-support (you may need to click on "more")

**Pull request merged**
