### PR TITLE
WinGRASS-7.8.5-2-Setup-x86_64 published

### PR DESCRIPTION
**Pull request by landam**
New 64bit wingrass binary available (see https://github.com/OSGeo/grass/issues/1218)

### CODE REVIEW

**Comment by neteler** [comment]
Great, thanks. 
Given its importance, should we additionally write an extra news entry?

**Review by hellik — APPROVED** [review]

**Comment by hellik** [comment]
> Great, thanks.
> Given its importance, should we additionally write an extra news entry?

yes, would be good

**Comment by hellik** [comment]
And a post in the ML

**Comment by landam** [comment]
No strong opinion here, probably post in the ML could be enough.

**Comment by hellik** [comment]
> 
> 
> No strong opinion here, probably post in the ML could be enough.

posted now in the user ML, see https://lists.osgeo.org/pipermail/grass-user/2021-January/082155.html

**Pull request merged**
