### PR TITLE
grass-docker logo: higher resolution version

### PR DESCRIPTION
**Pull request by neteler**
Replace tiny JPG with ~~PNG~~ larger JPG.

~~TODO: where is it linked into https://grass.osgeo.org/download/docker/~~

### CODE REVIEW

**Comment by veroandreo** [comment]
We would need to change all logos to png then, because they are expected to be jpg here: https://github.com/OSGeo/grass-website/blob/768f93b2786239fccc796336a7449f6cf2b62468/themes/grass/layouts/download/list.html#L43

**Comment by neteler** [comment]
Ah, I see. Re-added JPG again.

**Comment by veroandreo** [comment]
Did you check building the site? This is what I get here:

image

There's no size instruction for the img tag, so it takes it as is... I can try adding width and see what happens

**Comment by veroandreo** [comment]
Setting width to the other logos width (to avoid they look pixelated), I get this:

image

which I assume is what you wanted to change... perhaps actually editing the svg of the docker+grass logo (or re-doing it, I didn't find it in the website) by adding a larger grass logo there will fix it...

**Comment by neteler** [comment]
> Did you check building the site?

Actually I didn't. I hoped for auto-scaling...

Ok, we can also drop this PR.

**Comment by neteler** [comment]
> svg of the docker+grass logo

So my knowledge this does not exist. I (back then) compiled it from PNG logos, lacking a docker SVG.

**Comment by neteler** [comment]
I have created a draft high-res version:

PNG:
grass-docker-logo

SVG:
grass-docker-logo

**Comment by neteler** [comment]
Sizes fixed, too:

image

and:

image

**Comment by veroandreo** [comment]
Looks good!! Go ahead and merge :)

**Pull request merged**
