### PR TITLE
Search engines: local and DuckDuckgo

### PR DESCRIPTION
**Pull request by neteler**
Awaiting #131 to become ready, here an **interim solution** which addesses #19:
- new page https://grass.osgeo.org/about/search/ with menu entry under "About"
   - Web site search is done locally (the preview looks so-so but it doesn't slow down the site)
   - Manual pages search: via DuckDuckgo unless a better solution is implemented

To show this PR at work I have implemented it on the server.

On mobile devices it looks like this:

image

The code comes from here: [Volltextsuche für HUGO](https://weitblick.org/post/simple-static-site-search-hugo-jamstack/) (sorry, in German language - try to [machine translate it](https://translate.google.com/translate?sl=auto&tl=en&u=https://weitblick.org/post/simple-static-site-search-hugo-jamstack/)).

### CODE REVIEW

**Comment by lucadelu** [comment]
I looked at the code but I was not able to test it, I would like to do in the next days.
For manuals we could create during compilation a JSON file like the one done for the website and read info from it.

**Comment by lucadelu** [comment]
I tested it and it seems work properly, there is only a problem. If you switch from AND to OR without any work in the search field it return  `undefined` that it is not beautiful to see. I tried to look on the problem but I was not able to find the solution. I'll try to look on it next day.

**Comment by neteler** [comment]
I have reverted the patch on the server (it was there for a month locally applied to see how well it works) as it breaks our RSS feed (https://grass.osgeo.org/index.xml) which was reported in issue #247.

Hence: this PR needs a change to not break RSS (or, we improve the open #131). In any case, we need a "search" field!

**Comment by veroandreo** [comment]
Search added in https://github.com/OSGeo/grass-website/pull/334, closing

**Pull request closed without merging**
