### PR TITLE
Old news migrated from https://grass.osgeo.org/announces/

### PR DESCRIPTION
**Pull request by neteler**
Continuation of (old) news migration... from https://grass.osgeo.org/announces/

### CODE REVIEW

**Comment by neteler** [comment]
... still 17 more to come, please don't merge yet.

**Comment by neteler** [comment]
Done.
I didn't fix/check all links but I guess it is ok like that...

**Comment by neteler** [comment]
If there are no objections, I'd merge.

**Comment by veroandreo** [comment]
Yes, go ahead :)

**Pull request merged**
